import 'bootstrap/dist/css/bootstrap.min.css';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import Chart from 'chart.js/auto';
import './styles.css';

const money=n=>`৳ ${Number(n||0).toLocaleString('en-BD',{maximumFractionDigits:2})}`;
const today=()=>new Date().toISOString().slice(0,10);
async function api(url,opts={}){const r=await fetch('/api'+url,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d;}

function ChartBox({type,data,options}){const ref=useRef(null);useEffect(()=>{if(!ref.current)return;const c=new Chart(ref.current,{type,data,options});return()=>c.destroy()},[type,JSON.stringify(data),JSON.stringify(options)]);return <canvas ref={ref}/>}

class AppErrorBoundary extends React.Component{
  constructor(props){super(props);this.state={error:null}}
  static getDerivedStateFromError(error){return {error}}
  componentDidCatch(error,info){console.error('PFTracker page error:',error,info)}
  render(){if(this.state.error)return <div className="page-error"><div className="page-error-card"><h2>This page hit an error</h2><p>The application is still running. The error was caught so the whole screen does not go blank.</p><code>{this.state.error.message||'Unknown error'}</code><button className="primary" onClick={()=>this.setState({error:null})}>Try again</button></div></div>;return this.props.children}
}

function Auth({onLogin}){const [mode,setMode]=useState('login'),[form,setForm]=useState({name:'',email:'',password:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setError('');setBusy(true);try{const fd=new FormData(e.currentTarget);const payload={email:String(fd.get('email')||'').trim(),password:String(fd.get('password')||'')};if(mode==='register')payload.name=String(fd.get('name')||'').trim();if(!payload.email||!payload.password||(mode==='register'&&!payload.name)){throw new Error(mode==='register'?'Name, email and a password of at least 6 characters are required.':'Email and password are required.')}if(payload.password.length<6)throw new Error('Password must be at least 6 characters.');const d=await api(mode==='login'?'/auth/login':'/auth/register',{method:'POST',body:JSON.stringify(payload)});onLogin(d.user)}catch(e){setError(e.message)}finally{setBusy(false)}};return <div className="auth-page"><div className="auth-card"><div className="brand big"><b>PF</b>Tracker</div><p className="muted">Personal Finance Expense Tracker</p><div className="tabs"><button type="button" className={mode==='login'?'active':''} onClick={()=>{setMode('login');setError('')}}>Login</button><button type="button" className={mode==='register'?'active':''} onClick={()=>{setMode('register');setError('')}}>Create account</button></div><form onSubmit={submit}>{mode==='register'&&<label>Full name<input name="name" autoComplete="name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>Email<input name="email" type="email" autoComplete="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input name="password" type="password" autoComplete={mode==='register'?'new-password':'current-password'} required minLength={6} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{error&&<div className="alert error">{error}</div>}<button className="primary wide" disabled={busy}>{busy?'Please wait…':mode==='login'?'Login':'Create account'}</button></form><button type="button" className="demo-link" onClick={()=>setForm({name:'',email:'demo@pftracker.local',password:'Demo@12345'})}>Use demo credentials</button></div></div>}

function Layout({user,onLogout,page,setPage,children}){const items=[['dashboard','Dashboard','▦'],['transactions','Transactions','⇅'],['income','Income','↗'],['expenses','Expenses','↘'],['categories','Categories','◆'],['reports','Reports & Analytics','◉'],['monthly','Monthly Summary','▤'],['settings','Settings','⚙']];return <div className="app-shell"><aside><div className="brand"><b>PF</b>Tracker</div><div className="nav">{items.map(([id,n,ic])=><button key={id} className={page===id?'selected':''} onClick={()=>setPage(id)}><span>{ic}</span>{n}</button>)}</div><div className="side-bottom"><div className="avatar">{user.name[0]?.toUpperCase()}</div><div><strong>{user.name}</strong><small>{user.email}</small></div><button onClick={onLogout}>Log out</button></div></aside><main><header><div><h1>{items.find(x=>x[0]===page)?.[1]||'Dashboard'}</h1><p>Personal Finance Expense Tracker</p></div>{page==='dashboard'&&<button className="primary" onClick={()=>window.dispatchEvent(new Event('load-demo'))}>Load Demo Data</button>}</header>{children}</main></div>}

function Modal({title,onClose,children}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={onClose}>×</button></div>{children}</div></div>}
function TransactionForm({item,categories,defaultType,onClose,onSaved}){const [f,setF]=useState({type:item?.type||defaultType||'expense',amount:item?.amount||'',category_id:item?.category_id||'',transaction_date:item?.transaction_date||today(),description:item?.description||''});const [err,setErr]=useState('');const submit=async e=>{e.preventDefault();try{await api(item?`/transactions/${item.id}`:'/transactions',{method:item?'PUT':'POST',body:JSON.stringify(f)});onSaved()}catch(e){setErr(e.message)}};const cats=categories.filter(c=>c.type===f.type||c.type==='both');return <form onSubmit={submit} className="form-grid">{err&&<div className="alert error full">{err}</div>}<label>Type<select value={f.type} onChange={e=>setF({...f,type:e.target.value,category_id:''})}><option value="expense">Expense</option><option value="income">Income</option></select></label><label>Amount (৳)<input type="number" min="0.01" step="0.01" required value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></label><label>Category<select value={f.category_id} onChange={e=>setF({...f,category_id:e.target.value})}><option value="">Uncategorized</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Date<input type="date" required value={f.transaction_date} onChange={e=>setF({...f,transaction_date:e.target.value})}/></label><label className="full">Description<textarea rows="3" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><div className="actions full"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Save transaction</button></div></form>}

function Dashboard({refresh,setPage}){
 const [d,setD]=useState(null),[error,setError]=useState('');
 const load=()=>{setError('');return api('/dashboard').then(setD).catch(e=>setError(e.message))};
 useEffect(()=>{
  const onDataChanged=()=>load();
  const onLoadDemo=async()=>{try{await api('/demo',{method:'POST'});await load();window.dispatchEvent(new Event('data-changed'))}catch(e){alert(e.message)}};
  load();window.addEventListener('data-changed',onDataChanged);window.addEventListener('load-demo',onLoadDemo);
  return()=>{window.removeEventListener('data-changed',onDataChanged);window.removeEventListener('load-demo',onLoadDemo)}
 },[refresh]);
 if(error)return <div className="panel"><h2>Dashboard could not load</h2><p className="muted">{error}</p><button className="primary" onClick={load}>Retry</button></div>;
 if(!d)return <div className="loading">Loading dashboard…</div>;
 return <><div className="cards"><Card label="Total Income" value={money(d.totals.income)} tone="green"/><Card label="Total Expense" value={money(d.totals.expense)} tone="red"/><Card label="Current Balance" value={money(d.totals.balance)} tone="blue"/><Card label="Savings Rate" value={`${d.totals.savingsRate.toFixed(1)}%`} tone="purple"/></div><div className="grid-2"><section className="panel"><div className="panel-title"><h2>Spending by Category</h2><button className="text-btn" onClick={()=>setPage('reports')}>View reports →</button></div>{d.category.length?<ChartBox type="doughnut" data={{labels:d.category.map(x=>x.name),datasets:[{data:d.category.map(x=>x.value)}]}} options={{responsive:true,plugins:{legend:{position:'bottom'}}}}/>:<Empty text="Add expenses to see your spending breakdown."/>}</section><section className="panel"><div className="panel-title"><h2>Recent Transactions</h2><button className="text-btn" onClick={()=>setPage('transactions')}>View all →</button></div><TransactionList rows={d.recent}/></section></div><section className="panel"><div className="panel-title"><h2>Monthly Summary</h2><button className="text-btn" onClick={()=>setPage('monthly')}>Open summary →</button></div>{d.monthly.length?<ChartBox type="bar" data={{labels:d.monthly.map(x=>x.month),datasets:[{label:'Income',data:d.monthly.map(x=>x.income)},{label:'Expense',data:d.monthly.map(x=>x.expense)}]}} options={{responsive:true,scales:{y:{beginAtZero:true}}}}/>:<Empty text="No monthly data yet."/>}</section></>
}
function Card({label,value,tone}){return <div className={`card ${tone}`}><span>{label}</span><strong>{value}</strong></div>}
function Empty({text}){return <div className="empty">{text}</div>}
function TransactionList({rows,onEdit,onDelete}){if(!rows.length)return <Empty text="No transactions found."/>;return <div className="tx-list">{rows.map(r=><div className="tx" key={r.id}><div className={`tx-icon ${r.type}`}>{r.type==='income'?'↗':'↘'}</div><div className="tx-main"><strong>{r.category_name||'Uncategorized'}</strong><span>{r.transaction_date} · {r.description||'No description'}</span></div><strong className={r.type==='income'?'positive':'negative'}>{r.type==='income'?'+':'−'}{money(r.amount)}</strong>{onEdit&&<button className="icon-btn" onClick={()=>onEdit(r)}>✎</button>}{onDelete&&<button className="icon-btn danger" onClick={()=>onDelete(r.id)}>×</button>}</div>)}</div>}

function Transactions({refresh,setRefresh,mode}){
 const [rows,setRows]=useState([]),[cats,setCats]=useState([]),[filters,setFilters]=useState({search:'',type:mode||'',category:'',start:'',end:''}),[edit,setEdit]=useState(null),[add,setAdd]=useState(false),[error,setError]=useState('');
 const load=()=>{setError('');return Promise.all([api('/transactions?'+new URLSearchParams(Object.fromEntries(Object.entries(filters).filter(([,v])=>v)))),api('/categories')]).then(([a,b])=>{setRows(Array.isArray(a)?a:[]);setCats(Array.isArray(b)?b:[])}).catch(e=>setError(e.message))};
 useEffect(()=>{load()},[JSON.stringify(filters),refresh]);
 const del=async id=>{if(confirm('Delete this transaction?')){try{await api('/transactions/'+id,{method:'DELETE'});setRefresh(x=>x+1);window.dispatchEvent(new Event('data-changed'))}catch(e){setError(e.message)}}};
 return <><div className="page-alert-wrap">{error&&<div className="alert error page-alert"><strong>Could not load records:</strong> {error} <button type="button" className="text-btn" onClick={load}>Retry</button></div>}</div><div className="toolbar"><input placeholder="Search description or category…" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><select value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option value="">All types</option><option value="income">Income</option><option value="expense">Expense</option></select><select value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option value="">All categories</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="date" value={filters.start} onChange={e=>setFilters({...filters,start:e.target.value})}/><input type="date" value={filters.end} onChange={e=>setFilters({...filters,end:e.target.value})}/><button type="button" className="primary" onClick={()=>setAdd(true)}>+ Add {mode==='income'?'income':mode==='expense'?'expense':'transaction'}</button></div><section className="panel"><div className="panel-title"><h2>{mode==='income'?'Income Records':mode==='expense'?'Expense Records':'Transaction History'}</h2><span className="muted">{rows.length} record{rows.length===1?'':'s'}</span></div><TransactionList rows={rows} onEdit={setEdit} onDelete={del}/></section>{(add||edit)&&<Modal title={edit?'Edit transaction':'Add transaction'} onClose={()=>{setAdd(false);setEdit(null)}}><TransactionForm item={edit} categories={cats} defaultType={mode} onClose={()=>{setAdd(false);setEdit(null)}} onSaved={()=>{setAdd(false);setEdit(null);setRefresh(x=>x+1);window.dispatchEvent(new Event('data-changed'))}}/></Modal>}</>
}
function Categories({refresh,setRefresh}){
 const [rows,setRows]=useState([]),[f,setF]=useState({name:'',type:'expense'}),[edit,setEdit]=useState(null),[error,setError]=useState('');
 const load=()=>api('/categories').then(x=>setRows(Array.isArray(x)?x:[])).catch(e=>setError(e.message));useEffect(()=>{load()},[refresh]);
 const save=async e=>{e.preventDefault();try{await api(edit?`/categories/${edit.id}`:'/categories',{method:edit?'PUT':'POST',body:JSON.stringify(f)});setF({name:'',type:'expense'});setEdit(null);setRefresh(x=>x+1);window.dispatchEvent(new Event('data-changed'))}catch(e){setError(e.message)}};
 const del=async id=>{if(confirm('Delete this category? Transactions will become uncategorized.')){try{await api('/categories/'+id,{method:'DELETE'});setRefresh(x=>x+1);window.dispatchEvent(new Event('data-changed'))}catch(e){setError(e.message)}}};
 return <><div className="page-alert-wrap">{error&&<div className="alert error page-alert"><strong>Could not load categories:</strong> {error} <button type="button" className="text-btn" onClick={load}>Retry</button></div>}</div><div className="grid-2"><section className="panel"><div className="panel-title"><h2>{edit?'Edit category':'Create category'}</h2></div><form onSubmit={save} className="stack"><label>Category name<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Type<select value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option value="expense">Expense</option><option value="income">Income</option><option value="both">Both</option></select></label><div className="actions"><button type="submit" className="primary">{edit?'Update':'Add category'}</button>{edit&&<button type="button" className="secondary" onClick={()=>{setEdit(null);setF({name:'',type:'expense'})}}>Cancel</button>}</div></form></section><section className="panel"><div className="panel-title"><h2>Your categories</h2><span className="muted">{rows.length} total</span></div><div className="category-list">{rows.map(c=><div className="category-row" key={c.id}><div><strong>{c.name}</strong><span className={`badge ${c.type}`}>{c.type}</span></div><div><button type="button" className="icon-btn" onClick={()=>{setEdit(c);setF({name:c.name,type:c.type})}}>✎</button><button type="button" className="icon-btn danger" onClick={()=>del(c.id)}>×</button></div></div>)}</div></section></div></>
}

function Reports(){const [d,setD]=useState(null);useEffect(()=>{api('/reports').then(setD)},[]);if(!d)return <div className="loading">Loading reports…</div>;return <><div className="grid-2"><section className="panel"><h2>Income vs Expense</h2><ChartBox type="bar" data={{labels:d.monthly.map(x=>x.month),datasets:[{label:'Income',data:d.monthly.map(x=>x.income)},{label:'Expense',data:d.monthly.map(x=>x.expense)}]}} options={{responsive:true,scales:{y:{beginAtZero:true}}}}/></section><section className="panel"><h2>Expense by Category</h2><ChartBox type="pie" data={{labels:d.byCategory.filter(x=>x.type==='expense').map(x=>x.name||'Uncategorized'),datasets:[{data:d.byCategory.filter(x=>x.type==='expense').map(x=>x.total)}]}} options={{responsive:true,plugins:{legend:{position:'bottom'}}}}/></section></div><section className="panel"><h2>Category Breakdown</h2><div className="table-wrap"><table><thead><tr><th>Category</th><th>Type</th><th>Total</th></tr></thead><tbody>{d.byCategory.map((r,i)=><tr key={i}><td>{r.name||'Uncategorized'}</td><td><span className={`badge ${r.type}`}>{r.type}</span></td><td>{money(r.total)}</td></tr>)}</tbody></table></div></section></>}

function Monthly(){const [d,setD]=useState(null);useEffect(()=>{api('/reports').then(x=>setD(x.monthly))},[]);if(!d)return <div className="loading">Loading summary…</div>;return <section className="panel"><div className="panel-title"><h2>Monthly Financial Summary</h2><span className="muted">Income, expenses and net position</span></div><div className="table-wrap"><table><thead><tr><th>Month</th><th>Income</th><th>Expense</th><th>Net</th><th>Savings %</th></tr></thead><tbody>{d.map(r=>{const net=r.income-r.expense;return <tr key={r.month}><td>{r.month}</td><td className="positive">{money(r.income)}</td><td className="negative">{money(r.expense)}</td><td><strong>{money(net)}</strong></td><td>{r.income?((net/r.income)*100).toFixed(1):'0.0'}%</td></tr>})}</tbody></table></div></section>}

function Settings({user,onLogout}){const [msg,setMsg]=useState('');return <div className="grid-2"><section className="panel"><h2>Profile</h2><div className="profile"><div className="profile-avatar">{user.name[0]}</div><div><h3>{user.name}</h3><p>{user.email}</p><small>Account created locally and protected by session-based access.</small></div></div></section><section className="panel"><h2>Demo & project tools</h2><p className="muted">Use the demo data button on the dashboard to populate an empty account with realistic fictional records for presentation/testing.</p>{msg&&<div className="alert">{msg}</div>}<button className="secondary" onClick={()=>setMsg('Your data stays in the local SQLite database inside this project.')}>About local storage</button><button className="danger-btn" onClick={onLogout}>Log out</button></section></div>}

function App(){const [user,setUser]=useState(null),[page,setPage]=useState('dashboard'),[refresh,setRefresh]=useState(0);useEffect(()=>{api('/auth/me').then(x=>setUser(x.user)).catch(()=>setUser(false))},[]);if(user===null)return <div className="loading">Starting PFTracker…</div>;if(user===false)return <Auth onLogin={setUser}/>;const logout=async()=>{await api('/auth/logout',{method:'POST'});setUser(false)};const content=page==='dashboard'?<Dashboard refresh={refresh} setPage={setPage}/>:page==='transactions'?<Transactions refresh={refresh} setRefresh={setRefresh}/>:page==='income'?<Transactions mode="income" refresh={refresh} setRefresh={setRefresh}/>:page==='expenses'?<Transactions mode="expense" refresh={refresh} setRefresh={setRefresh}/>:page==='categories'?<Categories refresh={refresh} setRefresh={setRefresh}/>:page==='reports'?<Reports/>:page==='monthly'?<Monthly/>:<Settings user={user} onLogout={logout}/>;return <Layout user={user} onLogout={logout} page={page} setPage={setPage}><AppErrorBoundary key={page}>{content}</AppErrorBoundary></Layout>}

createRoot(document.getElementById('root')).render(<App/>);
